apiVersion: v1
kind: Pod
metadata:
  name: cm-secret-pod
spec:
  containers:
    - name: busybox
      image: busybox

      command: ["sh", "-c", "while true; do echo ConfigMap is $CONFIGMAPVAR and secret is $SECRETVAR; sleep 10; done"]
      env:
        - name: CONFIGMAPVAR
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: name
        - name: SECRETVAR
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_PASS