apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deploypod
  template:
    metadata:
      name: busybox-pod
      labels:
        name: deploypod
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          volumeMounts:
            - mountPath: "/sreekanth"
              name: my-storage

      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: my-second-pvc # Need to create PVC before providing this name






      