apiVersion: v1
kind: Pod
metadata:
  name: liveness-httppod
spec:
  containers:
    - name: liveness-httppod
      image: nginx
      livenessProbe:
        httpGet:
          port: 80
          path: /siva
        initialDelaySeconds: 5
        periodSeconds: 5

  