
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-second-pvc
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi