apiVersion: v1
kind: Pod
metadata:
  name: resourcequota
spec:
  containers:
    - name: quotacont
      image: busybox
      command:
        - "sh"
        - "-c"
        - "echo kubernetes!!! & sleep 3600"
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "250m"

