apiVersion: v1
kind: Pod
metadata:
  name: always-pod
spec:
  restartPolicy: Always  # OnFailure , Never
  containers:
    - name: always-cont
      image: nginx
      command:
        - "sh"
        - "-c"
        - "echo restart policy!! && sleep 10"