apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-storage
spec:
  storageClassName: 'apps'
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
     storage: 1Gi
  gcePersistentDisk:
    pdName: disk01
    fsType: ext4

